version: "3.8"
services:

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_RUN_RELOAD: 1
      FLASK_RUN_DEBUGGER: 0
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
      command: flask run
